version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    build: .
    ports:
      - 13000:3000
  
  frontend:
    build: ../client
    environment:
      - VITE_API_URL=http://localhost:13000
    ports:
      - 5173:5173
    depends_on:
      - app
    volumes:
      - ../client:/app
      - /app/node_modules